### ISSUE TITLE
Getting error when passing body object

### ISSUE THREAD

**Issue by skillmatic-co** [klaviyo/klaviyo-api-ruby#15]
I'm getting this error:

```Response body: {"errors":[{"id":"51c07451-b09a-4e77-a460-13cd0b920a28","status":400,"code":"invalid","title":"Invalid input.","detail":"The payload provided in the request is invalid.","source":{"pointer":"/data"},"meta":{}}]}```

When trying to call:

```@event = KlaviyoAPI::Events.create_event(body)```

My body object looks like this:

```
body = {
	data: {
		type: 'event',
		attributes: {
			properties: {
				registryID: @registry.id,
				registryKind: @registry.kind
			},
			time: DateTime.now.new_offset(0).iso8601,
			value: 0,
			metric: {
				data: {
					type: 'metric',
					attributes: {
						name: "Created Registry"
					}
				}
			},
			profile: @profile
		}
	}
}
```

Any idea what the issue is?

**Comment by cpcurtis1218** [comment]
Hi there, the data body itself is formatted correctly so I suspect that the issue is with the way the profile object is formatted.  The profile itself should be formatted as follows:

`
profile: {
  data: {
    type: "profile",
    id: @klaviyo_profile_id
    attributes: {
      email: @email,
      phone_number: @phone,
      external_id: @external_id
    }
  }
}
`
Please note that the "id" and the "external_id" are different.  The "id" field is for the Klaviyo id of the profile, while the "external_id" can be whatever value you'd like.  Both values are optional and do not need to be included.

For additional assistance with this issue I would recommend reaching out to our Support team who will be able to take a closer look at the specifics of the request in your Klaviyo account.

**Comment by skillmatic-co** [comment]
The profile object I'm passing is the exact response I'm getting from `get_profile`. Shouldn't that be formatted exactly as needed?

The error doesn't seem very verbose or relevant or helpful.

**Comment by cpcurtis1218** [comment]
The profile format in the `create_event` request is different from the `profile` of the `get_profile` response.  `get_profile` returns JSON and so that will need to be parsed into the necessary profile object in the `create_event` request.  This is helpful feedback that I'll pass along.

**Comment by skillmatic-co** [comment]
That was my issue, once I manually built the `profile` object it worked. I guess I assumed I would be able to pass it what was returned in the `get_profile` response.
